node28
Bulk In - Testing Framework
QE
Running Testing_Framework on womble with md
04/06/2021 14:10:48
--------------------------------------------------------
model: GAP_inF_1
args:
Analysing Model@ GAP_inF_1
share_dir /home/lls34/GitHub/01_PhD/PhD_Code/submodules/testing-framework/testing-framework/scripts/../share

###### START RUN Fri Jun  4 14:10:51 2021 ######
Model GAP_inF_1, Test bulk_In2O3_Ia3
Test run at 2021-06-04 14:10

model file: ../../models/GAP_inF_1/model.py
============================================================
Traceback (most recent call last):
  File "../../../scripts/run-model-test.py", line 118, in <module>
    sys.stdout.write(open(model_file).read())
FileNotFoundError: [Errno 2] No such file or directory: '../../models/GAP_inF_1/model.py'
share_dir /home/lls34/GitHub/01_PhD/PhD_Code/submodules/testing-framework/testing-framework/scripts/../share

###### START RUN Fri Jun  4 14:10:53 2021 ######
Model GAP_inF_1, Test bulk_In2O3_R3c
Test run at 2021-06-04 14:10

model file: ../../models/GAP_inF_1/model.py
============================================================
Traceback (most recent call last):
  File "../../../scripts/run-model-test.py", line 118, in <module>
    sys.stdout.write(open(model_file).read())
FileNotFoundError: [Errno 2] No such file or directory: '../../models/GAP_inF_1/model.py'
share_dir /home/lls34/GitHub/01_PhD/PhD_Code/submodules/testing-framework/testing-framework/scripts/../share

###### START RUN Fri Jun  4 14:10:54 2021 ######
Model GAP_inF_1, Test bulk_In2O3_Pbca
Test run at 2021-06-04 14:10

model file: ../../models/GAP_inF_1/model.py
============================================================
Traceback (most recent call last):
  File "../../../scripts/run-model-test.py", line 118, in <module>
    sys.stdout.write(open(model_file).read())
FileNotFoundError: [Errno 2] No such file or directory: '../../models/GAP_inF_1/model.py'
share_dir /home/lls34/GitHub/01_PhD/PhD_Code/submodules/testing-framework/testing-framework/scripts/../share

###### START RUN Fri Jun  4 14:10:55 2021 ######
Model GAP_inF_1, Test bulk_In2O3_Pbcn
Test run at 2021-06-04 14:10

model file: ../../models/GAP_inF_1/model.py
============================================================
Traceback (most recent call last):
  File "../../../scripts/run-model-test.py", line 118, in <module>
    sys.stdout.write(open(model_file).read())
FileNotFoundError: [Errno 2] No such file or directory: '../../models/GAP_inF_1/model.py'
share_dir /home/lls34/GitHub/01_PhD/PhD_Code/submodules/testing-framework/testing-framework/scripts/../share

###### START RUN Fri Jun  4 14:10:57 2021 ######
Model GAP_inF_1, Test phonons_In2O3_Ia3
Test run at 2021-06-04 14:10

model file: ../../models/GAP_inF_1/model.py
============================================================
Traceback (most recent call last):
  File "../../../scripts/run-model-test.py", line 118, in <module>
    sys.stdout.write(open(model_file).read())
FileNotFoundError: [Errno 2] No such file or directory: '../../models/GAP_inF_1/model.py'
share_dir /home/lls34/GitHub/01_PhD/PhD_Code/submodules/testing-framework/testing-framework/scripts/../share

###### START RUN Fri Jun  4 14:10:58 2021 ######
Model GAP_inF_1, Test bulk_In
Test run at 2021-06-04 14:10

model file: ../../models/GAP_inF_1/model.py
============================================================
Traceback (most recent call last):
  File "../../../scripts/run-model-test.py", line 118, in <module>
    sys.stdout.write(open(model_file).read())
FileNotFoundError: [Errno 2] No such file or directory: '../../models/GAP_inF_1/model.py'
