Model ACE_B14_N7_rid_1.10, Test bulk_Si_diamond
Test run at 2020-08-06 21:50

model file: ../../models/ACE_B14_N7_rid_1.10/model.py
============================================================
Traceback (most recent call last):
  File "../../../scripts/run-model-test.py", line 108, in <module>
    sys.stdout.write(open(model_file).read())
FileNotFoundError: [Errno 2] No such file or directory: '../../models/ACE_B14_N7_rid_1.10/model.py'
