Model ACE_N7_18_rrqr_E-12, Test point_defect_Si_interstitial_tetr
Test run at 2020-08-05 13:36

model file: ../../models/ACE_N7_18_rrqr_E-12/model.py
============================================================
import pyjulip
import os
import glob

model_dir = os.path.dirname(os.path.realpath(__file__))
pot_name = glob.glob(os.path.join(model_dir,"*.json"))[0]

calculator = pyjulip.ACE(pot_name)

no_checkpoint = True

name = "ACE"
============================================================
test file: /Users/Cas/gits/testing-framework/scripts/../tests/Si/point_defect_Si_interstitial_tetr/test.py
============================================================
Traceback (most recent call last):
  File "../../../scripts/run-model-test.py", line 114, in <module>
    sys.stdout.write(open(test_file).read())
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Cas/gits/testing-framework/scripts/../tests/Si/point_defect_Si_interstitial_tetr/test.py'
